### PR TITLE
Force non-executabe stack on linux

### PR DESCRIPTION
**Pull request by pavel-kokolemin**
Please merge after https://github.com/BlockSettle/common/pull/2102

### CODE REVIEW

**Comment by Ation** [comment]
Why do we need this? OS X - provide that by default and you need to explicitly specify that you want to have executable stack. Same goes for windows. For gcc it looks like this is a default for quite some time.
So for binaries we don't need this for sure. And we will never distribute with shared libraries. As for me - this will not change anything at best.
Can you prove me wrong?

**Comment by pavel-kokolemin** [comment]
I checked and server binaries (and staging terminal builds) have executabe stack:
```
$ scanelf -e /usr/bin/blocksettle
 TYPE   STK/REL/PTL FILE 
ET_DYN RWX R-- RW- /usr/bin/blocksettle
```
More info on that - https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md

**Comment by pavel-kokolemin** [comment]
And after this PR:
```
$ scanelf -e terminal/build_terminal/Debug/bin/blocksettle   
 TYPE   STK/REL/PTL FILE 
ET_DYN RW- RW- RW- /home/admin0/rep/fast/terminal/build_terminal/Debug/bin/blocksettle
```

**Comment by Ation** [comment]
Valid point on linux. Get same results with execstack tool. Still not sure about OSX. Very same documentation for bitcoin core have nothing related for OSX mentioned.

**Comment by pavel-kokolemin** [comment]
I copied that fragment from https://github.com/intel/caffe
I guess they know what they are doing.

**Review by Ation — APPROVED** [review]

**Pull request merged**
